version: "3.8"

services:
  spark-job:
    build:
      context: .
      dockerfile: dockerfiles/spark-job.dockerfile
    volumes:
      - events:/events
      - ./output:/output
      - ./data:/data
      - ./src:/src
      - ./logs:/logs      
    ports:
      - "4040:4040"      
    environment:
      - PYSPARK_PYTHON=python3.7

  spark-history-server:
    build:
      context: .
      dockerfile: dockerfiles/logs.dockerfile
    volumes:
      - events:/events      
    ports:
      - "18080:18080"
    environment:
      - PYSPARK_PYTHON=python3.7
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer --properties-file /config/spark.conf
      
  jupyter:
    image: jupyter/pyspark-notebook:spark-3.3.1
    ports:
      - '8888:8888'
    volumes:
      - ./output:/output
      - ./data:/data
      - ./src:/home/jovyan/src      
      - ./notebooks:/home/jovyan/work   

volumes:
  events:
    external: true
    